/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semaforo;

import javax.swing.ImageIcon;

/**
 *
 * @author pablo
 */
public class Semaforo1 extends javax.swing.JFrame {

    private int Cambiar=1;
    /**
     * Creates new form Semaforo1
     */
    public Semaforo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen1 = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen3 = new javax.swing.JLabel();
        lblSemaforo = new javax.swing.JLabel();
        lbnCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ROJO.jpg"))); // NOI18N

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/AMARILLO.jpg"))); // NOI18N

        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/VERDE.jpg"))); // NOI18N

        lblSemaforo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSemaforo.setForeground(new java.awt.Color(204, 0, 0));
        lblSemaforo.setText("SEMAFORO");

        lbnCambiar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbnCambiar.setForeground(new java.awt.Color(102, 0, 0));
        lbnCambiar.setText("CAMBIAR");
        lbnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbnCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblSemaforo)
                            .addGap(340, 340, 340))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(635, 635, 635)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbnCambiar)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblSemaforo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbnCambiarActionPerformed
        // TODO add your handling code here:
lblSemaforo.setText(String.valueOf(Cambiar));

if (Cambiar == 1) {
    ImageIcon rojo= new ImageIcon
        ("C:\\Users\\pablo\\OneDrive\\Documentos\\NetBeansProjects\\Holamundovisual\\src\\resources\\ROJO.jpg");
   lblSemaforo.setIcon(rojo);
    Cambiar=2;   
    
} else if(Cambiar== 2) {
    ImageIcon amarillo = new ImageIcon
        ("C:\\Users\\pablo\\OneDrive\\Documentos\\NetBeansProjects\\Holamundovisual\\src\\resources\\AMARILLO.jpg");
    lblSemaforo.setIcon(amarillo);
    Cambiar=3;
} else if (Cambiar== 3) {
    ImageIcon verde= new ImageIcon
        ("C:\\Users\\pablo\\OneDrive\\Documentos\\NetBeansProjects\\Holamundovisual\\src\\resources\\VERDE.jpg");
    lblSemaforo.setIcon(verde);
    Cambiar=1;
} else {
    System.out.println("INCORRECTO");
}

lblSemaforo.setText("");

    }//GEN-LAST:event_lbnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semaforo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semaforo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JLabel lblSemaforo;
    private javax.swing.JButton lbnCambiar;
    // End of variables declaration//GEN-END:variables
}
